### PR TITLE
Added npm dependencies

### PR DESCRIPTION
**Pull request by micky2be**
To be able to use the generator the node script needs dependencies to be installed.

[Review on Reviewable](https://reviewable.io/reviews/apla/me.apla.cordova.app-preferences/48)

### CODE REVIEW

**Comment by mgcrea** [comment]
:+1:

**Comment by SomaticIT** [comment]
Dependencies should not be on the global package, they should be installed only when using `plugman`.
If you want to be able to build without installing any dependencies we need to use __hooks__.

Take a look at #50.

**Comment by micky2be** [comment]
You can put it under devDependencies. 
Like any npm package

**Comment by SomaticIT** [comment]
Eventually but there are already in file `bin/package.json` ([Source](https://github.com/apla/me.apla.cordova.app-preferences/blob/master/bin/package.json)).

**Comment by micky2be** [comment]
Which are not installed through a npm install command. 
I cannot use your modile as a npm dependency.

**Comment by mgcrea** [comment]
I agree with @micky2be, the module is unusable in it's current state.

**Comment by apla** [comment]
@mgcrea , @micky2be Sorry about that. Actually most of the things I wanted to implement is in #50, but I very limited in time. I'll hope to fix all things this Sunday and add a Travis job.

**Comment by apla** [comment]
@mgcrea , @micky2be fixed in 0.7.4 (#53, #55, #57). Please check it out.

**Pull request closed without merging**
