### PR TITLE
Check the version of the installed platform and return the correct pa…

### PR DESCRIPTION
**Pull request by vash15**
Check the version of the installed platform and return the correct path of the resources.

Bugfix issue #135

### CODE REVIEW

**Comment by vash15** [comment]
I found other errors during installation and cleaning

**Comment by mapicard** [comment]
Having the same issue. How can we get an updated version of the plugin ?

**Comment by vash15** [comment]
I'm sorry, I create a new pull #137

**Comment by mapicard** [comment]
ok. Can I install this new version in my ionic project ? How? tx.

**Comment by vash15** [comment]
I don't use ionic, but I think it is sufficient to execute the command:

`cordova plugin add https://github.com/vash15/me.apla.cordova.app-preferences#master`

to install the pull request.

EDIT:
for ionic the command is:
`ionic cordova plugin add https://github.com/vash15/me.apla.cordova.app-preferences#master`
try it

**Comment by mapicard** [comment]
one step further since `'Installing "...app-preferences" for Android' ` does'nt give error but now I get
UnhandledPromiseRejection ENOENT no such file for 'resources/screen' !!! ;-(

**Comment by mapicard** [comment]
All errors fixed. Install is now 100% error free. tx.
ps: 'resources/screen' error had nothing to do with this plugin.

**Pull request closed without merging**
