### PR TITLE
Automate plugin processing using hooks and automate ios xcodeproj insertion

### PR DESCRIPTION
**Pull request by SomaticIT**
Hello,

This PR is linked to issue #46.
This PR allows to automatically generates natives bindings for `app-settings.json`.

To avoid code duplication and optimise build process I rewrote `lib/mobile_preferences.js` into separated context independent modules and using promises to be compatible with [Cordova Hooks](https://cordova.apache.org/docs/en/5.1.1/guide/appdev/hooks/index.html#link-7):
* `lib/filesystem.js`: Wrapper for native `fs` module using promise.
* `lib/settings.js`: Manage `app-settings.json` (get, create, remove).
* `lib/mappings.js`: Contains mapping definitions for each platforms.
* `lib/ios.js,lib/android.js`: Platform specific modules which expose build and clean methods.

All those modules have dependencies injected, allowing to use _Cordova inner require context_ when using plugin from cli (using hooks) and _node.js context_ when using the plugin from `plugman` (using `build-app-settings.js`).

Then I added 3 books :
* __after_plugin_add__: This hook is executed immediately after plugin installation. It adds a default `app-settings.json` to application.
* __before_plugin_rm__: This hook is executed just before plugin uninstallation. It clean every modifications done by the plugin (native code, XML configurations, etc.).
* __after_render__: This hook is executed immediately after each `prepare` opérations. It adds Native bindings and XML configuration to platforms projects using `app-settings.json` configuration.

I also moved existing tests to separates spec definitions in order to keep tests aligned with lib.

Possible Improvements :
* Only build prepared platform during __after_render__ book.
* Easily build new platforms by creating a new independent platform module (eg. build html form for Windows, blackberry, etc.).

Hope you will love it.

### CODE REVIEW

**Comment by apla** [comment]
I made one mistake and mixed two separate functionalities in one repo — plugin and preference generator. Until Cordova 5.0 this is not a problem because cordova using one repo for modules and you can install generators by running npm. Seems like your PR can handle this problem.

**Comment by SomaticIT** [comment]
Thanks for merging. 

I tested it with Cordova 5.3.3 and it seems to work with both `build-app-settings.js` and `cordova prepare`.

One thing I didn't report in my previous comment, I had to replace `libxmljs` dependency by `elementtree` which is user by cordova-lib internally.

Thanks.

**Comment by SomaticIT** [comment]
Did you published 0.7.2 release ?

**Comment by apla** [comment]
Yes, you can update via npm. I've already found `libxmljs` > `elementtree` migration and it is fine.

**Comment by SomaticIT** [comment]
Great ! Thanks.

**Comment by mohitmayank** [comment]
facing a small issue cause of this. 
if i remove and re-add android platform getting following error -

```
Error: ENOENT, open 'platforms/android/src/me/apla/cordova/AppPreferencesActivity.java'
    at Error (native)
```

perhaps moving the hook to before_build might help?

I don't add platform directory to version control. I also do customization on plugins and sometimes need to reset platform directory.

**Pull request merged**
